/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "shift" *)
(* src = "shift.sv:1.1-18.10" *)
module shift(reset_i, data_i, en_i, data_o, clk_i);
  (* src = "shift.sv:3.15-3.22" *)
  input reset_i;
  wire reset_i;
  (* src = "shift.sv:4.15-4.21" *)
  input data_i;
  wire data_i;
  (* src = "shift.sv:5.15-5.19" *)
  input en_i;
  wire en_i;
  (* src = "shift.sv:6.30-6.36" *)
  output [3:0] data_o;
  reg [3:0] data_o;
  (* src = "shift.sv:7.15-7.20" *)
  input clk_i;
  wire clk_i;
  (* \always_ff  = 32'd1 *)
  (* src = "shift.sv:10.1-16.4" *)
  always @(posedge clk_i)
    if (reset_i) data_o[0] <= 1'h0;
    else if (en_i) data_o[0] <= data_i;
  (* \always_ff  = 32'd1 *)
  (* src = "shift.sv:10.1-16.4" *)
  always @(posedge clk_i)
    if (reset_i) data_o[1] <= 1'h0;
    else if (en_i) data_o[1] <= data_o[0];
  (* \always_ff  = 32'd1 *)
  (* src = "shift.sv:10.1-16.4" *)
  always @(posedge clk_i)
    if (reset_i) data_o[2] <= 1'h0;
    else if (en_i) data_o[2] <= data_o[1];
  (* \always_ff  = 32'd1 *)
  (* src = "shift.sv:10.1-16.4" *)
  always @(posedge clk_i)
    if (reset_i) data_o[3] <= 1'h0;
    else if (en_i) data_o[3] <= data_o[2];
endmodule
