/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* hdlname = "dff" *)
(* src = "dff.sv:2.1-12.10" *)
module dff(clk_i, reset_i, d_i, en_i, q_o);
  (* src = "dff.sv:3.15-3.20" *)
  input clk_i;
  wire clk_i;
  (* src = "dff.sv:4.15-4.22" *)
  input reset_i;
  wire reset_i;
  (* src = "dff.sv:5.15-5.18" *)
  input d_i;
  wire d_i;
  (* src = "dff.sv:6.15-6.19" *)
  input en_i;
  wire en_i;
  (* src = "dff.sv:7.16-7.19" *)
  output q_o;
  reg q_o;
  (* src = "dff.sv:9.3-11.6" *)
  always @*
    if (en_i) q_o = d_i;
endmodule
