/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "counter" *)
(* src = "counter.sv:2.1-33.10" *)
module counter(reset_i, up_i, down_i, count_o, clk_i);
  (* src = "counter.sv:7.15-7.22" *)
  input reset_i;
  wire reset_i;
  (* src = "counter.sv:8.15-8.19" *)
  input up_i;
  wire up_i;
  (* src = "counter.sv:9.15-9.21" *)
  input down_i;
  wire down_i;
  (* src = "counter.sv:10.30-10.37" *)
  output [3:0] count_o;
  wire [3:0] count_o;
  (* src = "counter.sv:11.15-11.20" *)
  input clk_i;
  wire clk_i;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* src = "counter.sv:14.23-14.30" *)
  wire [3:0] count_d;
  (* src = "counter.sv:14.32-14.39" *)
  reg [3:0] count_q;
  assign _003_ = ~(count_q[3] & count_q[2]);
  assign count_d[0] = ~count_q[0];
  assign _012_ = ~count_q[2];
  assign _021_ = ~(_062_ & _063_);
  assign _022_ = ~(_066_ & _067_);
  assign _023_ = ~(_005_ & count_q[1]);
  assign _024_ = ~(_068_ & _069_);
  assign _025_ = ~(_011_ & count_d[0]);
  assign _026_ = ~(_070_ & _071_);
  assign _027_ = ~(_005_ & _012_);
  assign _028_ = ~(_072_ & _073_);
  assign _029_ = ~(count_q[1] & _074_);
  assign _030_ = ~(_016_ & _013_);
  assign _031_ = ~(_077_ & _078_);
  assign _032_ = ~(_030_ & _031_);
  assign _033_ = ~(_005_ & count_q[3]);
  assign _034_ = ~(_079_ & _080_);
  assign _035_ = ~(_081_ & _082_);
  assign _036_ = ~(_020_ & _017_);
  assign _037_ = ~(_085_ & _086_);
  assign _038_ = up_i & _055_;
  assign _039_ = count_q[1] & _056_;
  assign _040_ = _002_ & _057_;
  assign _041_ = _001_ & _058_;
  assign _042_ = down_i & _059_;
  assign _043_ = _060_ & _061_;
  assign _044_ = _007_ & _064_;
  assign _045_ = _006_ & _065_;
  assign _046_ = _023_ & _024_;
  assign _047_ = _025_ & _026_;
  assign _048_ = _027_ & _028_;
  assign _049_ = count_q[0] & _075_;
  assign _050_ = _014_ & _076_;
  assign _051_ = _033_ & _034_;
  assign _052_ = _013_ & _083_;
  assign _053_ = _018_ & _084_;
  assign _054_ = _036_ & _037_;
  assign _055_ = ~down_i;
  assign _056_ = ~count_q[0];
  assign _057_ = ~_003_;
  assign _058_ = ~_004_;
  assign _059_ = ~up_i;
  assign _060_ = ~count_q[1];
  assign _061_ = ~count_q[0];
  assign _062_ = ~count_q[3];
  assign _063_ = ~count_q[2];
  assign _064_ = ~_008_;
  assign _065_ = ~_009_;
  assign _066_ = ~_010_;
  assign _067_ = ~_005_;
  assign _068_ = ~_005_;
  assign _069_ = ~count_q[1];
  assign _070_ = ~_011_;
  assign _071_ = ~count_d[0];
  assign _072_ = ~_005_;
  assign _073_ = ~_012_;
  assign _074_ = ~_005_;
  assign _075_ = ~_011_;
  assign _076_ = ~_015_;
  assign _077_ = ~_016_;
  assign _078_ = ~_013_;
  assign _079_ = ~_005_;
  assign _080_ = ~count_q[3];
  assign _081_ = ~_005_;
  assign _082_ = ~_012_;
  assign _083_ = ~_016_;
  assign _084_ = ~_019_;
  assign _085_ = ~_020_;
  assign _086_ = ~_017_;
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[0] <= 1'h0;
    else if (_000_) count_q[0] <= count_d[0];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[1] <= 1'h0;
    else if (_000_) count_q[1] <= count_d[1];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[2] <= 1'h0;
    else if (_000_) count_q[2] <= count_d[2];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[3] <= 1'h0;
    else if (_000_) count_q[3] <= count_d[3];
  assign count_o = count_q;
  assign _001_ = _038_;
  assign _002_ = _039_;
  assign _004_ = _040_;
  assign _005_ = _041_;
  assign _006_ = _042_;
  assign _007_ = _043_;
  assign _008_ = _021_;
  assign _009_ = _044_;
  assign _010_ = _045_;
  assign _000_ = _022_;
  assign _011_ = _046_;
  assign count_d[1] = _047_;
  assign _013_ = _048_;
  assign _014_ = _029_;
  assign _015_ = _049_;
  assign _016_ = _050_;
  assign count_d[2] = _032_;
  assign _017_ = _051_;
  assign _018_ = _035_;
  assign _019_ = _052_;
  assign _020_ = _053_;
  assign count_d[3] = _054_;
endmodule
