/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "counter" *)
(* src = "counter.sv:2.1-33.10" *)
module counter(reset_i, up_i, down_i, count_o, clk_i);
  (* src = "counter.sv:7.15-7.22" *)
  input reset_i;
  wire reset_i;
  (* src = "counter.sv:8.15-8.19" *)
  input up_i;
  wire up_i;
  (* src = "counter.sv:9.15-9.21" *)
  input down_i;
  wire down_i;
  (* src = "counter.sv:10.30-10.37" *)
  output [3:0] count_o;
  wire [3:0] count_o;
  (* src = "counter.sv:11.15-11.20" *)
  input clk_i;
  wire clk_i;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "counter.sv:14.23-14.30" *)
  wire [3:0] count_d;
  (* src = "counter.sv:14.32-14.39" *)
  reg [3:0] count_q;
  assign count_d[0] = ~count_q[0];
  assign _001_ = ~count_q[1];
  assign _010_ = ~(_002_ & count_q[2]);
  assign _013_ = ~(up_i & down_i);
  assign _014_ = ~(_041_ & _042_);
  assign _015_ = ~(_002_ & _001_);
  assign _016_ = ~(_044_ & _045_);
  assign _017_ = ~(_003_ & count_d[0]);
  assign _018_ = ~(_046_ & _047_);
  assign _019_ = ~(_002_ & count_q[2]);
  assign _020_ = ~(_048_ & _049_);
  assign _021_ = ~(up_i & _050_);
  assign _022_ = ~(_051_ & _052_);
  assign _023_ = ~(_008_ & _004_);
  assign _024_ = ~(_055_ & _056_);
  assign _025_ = ~(_023_ & _024_);
  assign _026_ = ~(_005_ & count_q[3]);
  assign _027_ = ~(_057_ & _058_);
  assign _028_ = ~(_012_ & _009_);
  assign _029_ = ~(_061_ & _062_);
  assign _030_ = _013_ & _014_;
  assign _031_ = up_i & _043_;
  assign _032_ = _015_ & _016_;
  assign _033_ = _017_ & _018_;
  assign _034_ = _019_ & _020_;
  assign _035_ = count_q[0] & _053_;
  assign _036_ = _006_ & _054_;
  assign _037_ = _026_ & _027_;
  assign _038_ = _004_ & _059_;
  assign _039_ = _010_ & _060_;
  assign _040_ = _028_ & _029_;
  assign _041_ = ~up_i;
  assign _042_ = ~down_i;
  assign _043_ = ~down_i;
  assign _044_ = ~_002_;
  assign _045_ = ~_001_;
  assign _046_ = ~_003_;
  assign _047_ = ~count_d[0];
  assign _048_ = ~_002_;
  assign _049_ = ~count_q[2];
  assign _050_ = ~down_i;
  assign _051_ = ~_005_;
  assign _052_ = ~_001_;
  assign _053_ = ~_003_;
  assign _054_ = ~_007_;
  assign _055_ = ~_008_;
  assign _056_ = ~_004_;
  assign _057_ = ~_005_;
  assign _058_ = ~count_q[3];
  assign _059_ = ~_008_;
  assign _060_ = ~_011_;
  assign _061_ = ~_012_;
  assign _062_ = ~_009_;
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[0] <= 1'h0;
    else if (_000_) count_q[0] <= count_d[0];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[1] <= 1'h0;
    else if (_000_) count_q[1] <= count_d[1];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[2] <= 1'h0;
    else if (_000_) count_q[2] <= count_d[2];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[3] <= 1'h0;
    else if (_000_) count_q[3] <= count_d[3];
  assign count_o = count_q;
  assign _000_ = _030_;
  assign _002_ = _031_;
  assign _003_ = _032_;
  assign count_d[1] = _033_;
  assign _004_ = _034_;
  assign _005_ = _021_;
  assign _006_ = _022_;
  assign _007_ = _035_;
  assign _008_ = _036_;
  assign count_d[2] = _025_;
  assign _009_ = _037_;
  assign _011_ = _038_;
  assign _012_ = _039_;
  assign count_d[3] = _040_;
endmodule
