/* Generated by Yosys 0.57 (git sha1 3aca86049e79a165932e3e7660358376f45acaed, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "counter" *)
(* src = "counter.sv:2.1-33.10" *)
module counter(reset_i, up_i, down_i, count_o, clk_i);
  (* src = "counter.sv:7.15-7.22" *)
  input reset_i;
  wire reset_i;
  (* src = "counter.sv:8.15-8.19" *)
  input up_i;
  wire up_i;
  (* src = "counter.sv:9.15-9.21" *)
  input down_i;
  wire down_i;
  (* src = "counter.sv:10.30-10.37" *)
  output [3:0] count_o;
  wire [3:0] count_o;
  (* src = "counter.sv:11.15-11.20" *)
  input clk_i;
  wire clk_i;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* src = "counter.sv:14.23-14.30" *)
  wire [3:0] count_d;
  (* src = "counter.sv:14.32-14.39" *)
  reg [3:0] count_q;
  assign count_d[0] = ~count_q[0];
  assign _003_ = ~count_q[2];
  assign _012_ = ~(up_i & down_i);
  assign _013_ = ~(_040_ & _041_);
  assign _014_ = ~(_001_ & count_q[1]);
  assign _015_ = ~(_043_ & _044_);
  assign _016_ = ~(_002_ & count_d[0]);
  assign _017_ = ~(_045_ & _046_);
  assign _018_ = ~(_001_ & _003_);
  assign _019_ = ~(_047_ & _048_);
  assign _020_ = ~(count_q[1] & _049_);
  assign _021_ = ~(_007_ & _004_);
  assign _022_ = ~(_052_ & _053_);
  assign _023_ = ~(_021_ & _022_);
  assign _024_ = ~(_001_ & count_q[3]);
  assign _025_ = ~(_054_ & _055_);
  assign _026_ = ~(_056_ & _057_);
  assign _027_ = ~(_011_ & _008_);
  assign _028_ = ~(_060_ & _061_);
  assign _029_ = _012_ & _013_;
  assign _030_ = up_i & _042_;
  assign _031_ = _014_ & _015_;
  assign _032_ = _016_ & _017_;
  assign _033_ = _018_ & _019_;
  assign _034_ = count_q[0] & _050_;
  assign _035_ = _005_ & _051_;
  assign _036_ = _024_ & _025_;
  assign _037_ = _004_ & _058_;
  assign _038_ = _009_ & _059_;
  assign _039_ = _027_ & _028_;
  assign _040_ = ~up_i;
  assign _041_ = ~down_i;
  assign _042_ = ~down_i;
  assign _043_ = ~_001_;
  assign _044_ = ~count_q[1];
  assign _045_ = ~_002_;
  assign _046_ = ~count_d[0];
  assign _047_ = ~_001_;
  assign _048_ = ~_003_;
  assign _049_ = ~_001_;
  assign _050_ = ~_002_;
  assign _051_ = ~_006_;
  assign _052_ = ~_007_;
  assign _053_ = ~_004_;
  assign _054_ = ~_001_;
  assign _055_ = ~count_q[3];
  assign _056_ = ~_001_;
  assign _057_ = ~_003_;
  assign _058_ = ~_007_;
  assign _059_ = ~_010_;
  assign _060_ = ~_011_;
  assign _061_ = ~_008_;
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[0] <= 1'h1;
    else if (_000_) count_q[0] <= count_d[0];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[1] <= 1'h0;
    else if (_000_) count_q[1] <= count_d[1];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[2] <= 1'h0;
    else if (_000_) count_q[2] <= count_d[2];
  (* \always_ff  = 32'd1 *)
  (* src = "counter.sv:24.1-30.4" *)
  always @(posedge clk_i)
    if (reset_i) count_q[3] <= 1'h0;
    else if (_000_) count_q[3] <= count_d[3];
  assign count_o = count_q;
  assign _000_ = _029_;
  assign _001_ = _030_;
  assign _002_ = _031_;
  assign count_d[1] = _032_;
  assign _004_ = _033_;
  assign _005_ = _020_;
  assign _006_ = _034_;
  assign _007_ = _035_;
  assign count_d[2] = _023_;
  assign _008_ = _036_;
  assign _009_ = _026_;
  assign _010_ = _037_;
  assign _011_ = _038_;
  assign count_d[3] = _039_;
endmodule
